# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# NOTE, THIS FILE IS BEING USED by disabling Laptop display monitor behaviour when closing lid.
# See notes on Laptops.conf

# 1. Laptop built-in display
monitor = eDP-1, 2880x1800@60, auto, 1.67
# Saving laptop Battery
# monitor = eDP-1, 1920x1080@60, auto, 1

# 2. External DisplayPort monitor (primary, top-left origin)
monitor = DP-2, 1920x1080@200, 0x0, 1

# 3. HDMI monitor placed automatically to the left of DP-2
monitor = HDMI-A-1, 1680x1050@59.88Hz, auto-left, 1.5
